fr--newspaper: 3.75 
fr--book: 3.75
fr--technical: 3.75
fr--wiki: 3.75
fr--legi_written: 3.75
fr--dialogue: 3.75
fr--legi_spoken: 3.75
fr--legi_dialogue: 3.75
en--technical: 3.34
en--newspaper: 3.34
en--legi_written: 3.33
en--wiki: 3.34
en--forum: 3.33
en--book: 3.33
en--math: 3.33
en--dialogue: 3.33
en--legi_dialogue: 3.33
de--wiki: 0.66
de--legi_written: 0.66
de--book: 0.66
de--legi_dialogue: 0.66
es--wiki: 0.66
es--legi_written: 0.66
es--legi_dialogue: 0.66
es--book: 0.66
it--wiki: 0.66
it--legi_written: 0.66
it--book: 0.66
es-en--aligned: 0.685
it-en--aligned: 0.685
de-fr--aligned: 0.685
fr-en--aligned: 0.685
code--programming: 30.0
