code--programming: 30.0
de--book: 0.285
de--legi_dialogue: 0.285
de--legi_written: 0.285
de--web: 0.285
de--wiki: 0.285
de-fr--aligned: 1.428
en--book: 3.0
en--dialogue: 3.0
en--forum: 3.0
en--legi_dialogue: 3.0
en--legi_written: 3.0
en--math: 3.0
en--newspaper: 3.0
en--technical: 3.0
en--web: 3.0
en--wiki: 3.0
es--book: 0.285
es--legi_dialogue: 0.285
es--legi_written: 0.285
es--web: 0.285
es--wiki: 0.285
es-en--aligned: 1.428
fr--book: 3.33
fr--dialogue: 3.33
fr--legi_dialogue: 3.33
fr--legi_spoken: 3.33
fr--legi_written: 3.33
fr--newspaper: 3.33
fr--technical: 3.33
fr--web: 3.33
fr--wiki: 3.33
fr-en--aligned: 1.428
it--book: 0.357
it--legi_written: 0.357
it--web: 0.357
it--wiki: 0.357
it-en--aligned: 1.428
